### ISSUE TITLE
Using arc git config to sign commits

### ISSUE THREAD

**Issue by ZimmerD** [nfdi4plants/Quickstart#4]
The current version of the Quickstart, utilizes the global git config to sign commits. This can be quite confusing because git account and data plant account might differ. As a result, it is possible to mix identities (e.g., validate via DataPLANT account, sign commits with regular git account), which we might want to avoid. 

I talked to @kMutagene and we suggest to include a step at the beginning of the section "Arc sharing" that walks the user through the process of configuring the arc git config, e.g., via 

`arc config --global`

**Comment by Brilator** [comment]
Good point! Feel free to add the section and PR.

**Comment by Martin-Kuhl** [comment]
I will update the QuickStart in the next days and include all upcoming issues..

**Comment by ZimmerD** [comment]
Just talked to @HLWeil, he is just documenting the intended way of using the arc git config and will link the result of his work in this issue @Martin-Kuhl

**Comment by Brilator** [comment]
Might also make sense to move this into / parallel to the being developed "knowledgebase" on the hp. 
But should be abstracted from the deep-dive https://nfdi4plants.org/content/service/arccommander.html.

**Comment by HLWeil** [comment]
https://github.com/nfdi4plants/arcCommander/wiki/6.-ARC-Synchronization#62-setting-a-git-user
